# Setup
title:            20213079 Jeong Su Hyeon
email:            112jshjsh@kookmin.ac.kr
tagline:      '2021-2 유레카프로젝트 20213079 정수현'
# baseurl: "" # the subpath of your site, e.g. /blog
url:              "https://suhyun7890.github.io"
github_username:  suhyun7890
asset_url: /assets

# Build settings
plugins:
  - jekyll-feed

# Custom vars
comment:
  provider:        "discus"
  disqus:
    shortname:     "suhyun7890"
